language: go
dist: xenial

go:
  - 1.13.x

notifications:
  email: false

script:
  - go build -v

before_deploy:
  - tar -zcf terraform-provider-vscale.tar.gz terraform-provider-vscale

deploy:
  provider: releases
  api_key:
    secure: "YwFKVLoBk+sSN4UxhzN2TbfDfiWYxCluzLeCxrb6bNbT0ZH5iqGXUQp0PQgqCT6wY3Oi0PM0sDqZgqJwR7X3IbOeawM03WRTR1rPwG2RXghi/StflMbDVEeb7WzyHUqmH3aThMyNEisZIuVDtbUsGfv+wKhuUHz3YDgMzNbojUKKJrWlv6VvKY/16owXeV3M6PaTHt3ZjI9cCuEcbP2J1ZiJL6XAPLhcyk7+CNJ87L8qHFfcOO9VB11Ydcy/scqzTtANroYIZhfNtxLEZ0Kqj/brRzXi66tAYoajo9OuubXoMeOIqZ3+TM0yOcbkLmipu2W++f1QrPcDFbe3pix6DSa89XhLBf+RCQ4nwDEiy6bG+Te+4YbV3arEHuwUZmwO4cp2nFoV7D4kzY0qCXzTx6ayHXgqIkyoTKOjtbBJ3cIOEyYdW8dOmXWlDl1JXlXepxOO9yJO1p4uL8kSxE7y4v8wTdaCnoZnO1u27ZGmdgCfSPLX47Fmw18/neFNlGxKmirtmNTg0D2+1O6FwGvlPChN7jqOnXbaNI/AvcHjmJH/8T6z3+k7myg3PXEo6AUI9tWm7ssEOLD5vWwb6xBVgrix41zya3l6NdTOoMPYW/5uIl7SCewJgoxfXntkwohLSQ/jKQ924CXUMOd2flIs1OXtGtz8NGaDacg/eT2J+rE="
  skip_cleanup: true
  file: terraform-provider-vscale.tar.gz
